// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

/**
 * @title IGroth16Verifier
 * @notice Interface for Groth16 ZK-SNARK proof verification
 * @dev The actual implementation is auto-generated by snarkjs from the circuit
 *
 * Public signals (8 total):
 * [0] merkleRoot - Root of the deposit Merkle tree
 * [1] nullifierHash - Hash of the nullifier to prevent double-spending
 * [2] recipient - Stealth address to receive swap output
 * [3] relayer - Address of the relayer (0 if no relayer)
 * [4] relayerFee - Fee in basis points for the relayer
 * [5] swapAmountOut - Expected output amount from the swap
 * [6] depositAmount - Original deposit amount (constrained internally)
 * [7] commitment - The commitment hash (constrained internally)
 */
interface IGroth16Verifier {
    /**
     * @notice Verify a Groth16 proof
     * @param _pA Proof point A (G1)
     * @param _pB Proof point B (G2)
     * @param _pC Proof point C (G1)
     * @param _pubSignals Public signals array (8 elements)
     * @return True if the proof is valid
     */
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[8] calldata _pubSignals
    ) external view returns (bool);
}
